"""Updated customer_name

Revision ID: 9f1bda0e25e7
Revises: 20ee599f072a
Create Date: 2025-04-20 22:52:24.615897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f1bda0e25e7'
down_revision: Union[str, None] = '20ee599f072a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reservations_customer_name_key', 'reservations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('reservations_customer_name_key', 'reservations', ['customer_name'])
    # ### end Alembic commands ###
